### ISSUE TITLE
Problems rewriting some css url('') resources (case: IcoMoon Font)

### ISSUE THREAD

**Issue by creativeprogramming** [pagespeed/ngx_pagespeed#411]
I've icomoon installed at `/media/fontawesomeness/assets/icomoon/`

 `/media/fontawesomeness/assets/icomoon/style.css` contains this:

```css
@font-face {
	font-family: 'icomoon';
	src:url('fonts/icomoon.eot');
	src:url('fonts/icomoon.eot?#iefix') format('embedded-opentype'),
		url('fonts/icomoon.woff') format('woff'),
		url('fonts/icomoon.ttf') format('truetype'),
		url('fonts/icomoon.svg#icomoon') format('svg');
```
fonts are in:
 `/media/fontawesomeness/assets/icomoon/fonts/*`

With ngx_pagespeed I *sporadically* get wrong final requests like this:

 `http://mydomain.com/media/fontawesomeness/assets/font-awesome/css/media/fontawesomeness/assets/icomoon/fonts/icomoon.ttf `

instead of:

 `http://mydomain.com/media/fontawesomeness/assets/icomoon/fonts/icomoon.ttf `

the strange thing is that I get this problem *only on the .ttf and the .svg entry*:
```css
	url('fonts/icomoon.ttf') format('truetype'),
	url('fonts/icomoon.svg#icomoon') format('svg');
```
and not always! 
(**anyway the webfont always works in Chrome and FF**, I just noticed this failing http requests in the  in the network panel of the Chrome debug console)

P.S. I know  `url('uristring')` is not the standard CSS syntax 
(the correct one is:  `url(uristring) ` ) and removing the quotes from icomoon url()s  not fixed this problem, now in fact I've this:

```css
@font-face {
	font-family: 'icomoon';
	src:url(fonts/icomoon.eot);
	src:url(fonts/icomoon.eot?#iefix) format('embedded-opentype'),
		url(fonts/icomoon.woff) format('woff'),
		url(fonts/icomoon.ttf) format('truetype'),
		url(fonts/icomoon.svg#icomoon) format('svg');
	font-weight: normal;
	font-style: normal;
}
```

it happens only sometimes, that is strange. Maybe is due just to my particular configuration (or my bad) i'm not sure it's a pagespeed issue
