### ISSUE TITLE
rewrite_css for images doesn't work under media queries

### ISSUE THREAD

**Issue by VarunBatraIT** [pagespeed/ngx_pagespeed#969]
### Pagespeed Configuration

```
        pagespeed EnableFilters rewrite_images;
        pagespeed EnableFilters recompress_images;
        pagespeed ImageRecompressionQuality 80;
        pagespeed EnableFilters rewrite_css;
        pagespeed EnableFilters sprite_images;
        pagespeed EnableFilters rewrite_style_attributes;
```

### Original CSS

```css
.parallax-bg-4
{
  background-image: url(http://www.stumento.com/assets/parallax/mobile/writing-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg);
}
@media screen and (min-width: 768px)
{
  .parallax-bg-2
  {
    background-image: url(http://www.stumento.com/assets/parallax/mobile/writing-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg);
  }
}

```

### Current Output ###

Rewrite didn't happen for .parallax-bg-2

```css
.parallax-bg-4
{
  background-image: url(http://www.stumento.com/assets/parallax/mobile/xwriting-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg.pagespeed.ic.4zTzy_hob0.jpg);
}
@media screen and (min-width: 768px)
{
  .parallax-bg-2
  {
    background-image: url(http://www.stumento.com/assets/parallax/mobile/writing-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg);
  }
}

```

### Expected Output ###
Both of above files are same. Thus one should expect

```css
.parallax-bg-4
{
  background-image: url(http://www.stumento.com/assets/parallax/mobile/xwriting-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg.pagespeed.ic.4zTzy_hob0.jpg);
}
@media screen and (min-width: 768px)
{
  .parallax-bg-2
  {
    background-image: url(http://www.stumento.com/assets/parallax/mobile/xwriting-c4ed5b0467ca93a2a02d6141c6f9ed3c.jpg.pagespeed.ic.4zTzy_hob0.jpg);
  }
}

```

### Other Details ###

1. nginx version: nginx/1.8.0
2. X-Page-Speed:1.9.32.3-4448
3. Reference link https://developers.google.com/speed/pagespeed/module/filter-css-rewrite
4. Website URL http://StuMento.com/
